/**
 * XuanAo BaZi Commentary Engine
 * 440+ Classical Rules with Plain Language Explanations & English Translations
 */
const CommentaryEngine = (function() {
    'use strict';

    // All commentary categories with their rules
    // Each rule: { text: original, plain: plain language explanation, en: English, plainEn: plain English }
    const CATEGORIES = {
        personality: {
            name: '性格',
            nameEn: 'Personality',
            icon: '🧠',
            rules: [
                { text: '正印得地，心慈仁德，善于守成，慈善。',
                  plain: '你心地善良、仁慈宽厚，富有同情心，善于维护已有的成果，不喜冒险。',
                  en: 'Direct Resource properly positioned — kind-hearted, virtuous, adept at preservation, charitable.',
                  plainEn: 'You have a kind and compassionate nature. You are benevolent, generous, and excel at maintaining what you have rather than taking risks.' },
                { text: '偏印当权，多学少成，乐善好施，孤独之命。',
                  plain: '你聪明好学，但容易学得多而精得少。乐于助人，但内心常有孤独感。',
                  en: 'Indirect Resource in power — learns much but masters little, generous yet lonely.',
                  plainEn: 'You are intelligent and curious, but tend to spread yourself too thin. You enjoy helping others, yet often feel a sense of inner solitude.' },
                { text: '食神得力，擅长歌舞。',
                  plain: '你有艺术天赋，尤其在音乐、表演、娱乐方面有特长。',
                  en: 'Output strong — talented in singing and dancing, artistic expression.',
                  plainEn: 'You have natural artistic talent, especially in music, performance, and creative expression.' },
                { text: '偏财喜色，风流倜傥，慷慨大方，挥金如土。',
                  plain: '你大方慷慨，喜欢享受生活，对钱不太计较，但也容易花钱大手大脚。',
                  en: 'Indirect Wealth loves beauty — charming, generous, spends freely.',
                  plainEn: 'You are generous and enjoy the finer things in life. You don\'t worry too much about money, but can be prone to overspending.' },
                { text: '七杀有制，为人刚强。',
                  plain: '你性格刚强果断，有领导力和决断力，能克服困难实现目标。',
                  en: 'Seven Killings controlled — strong-willed and determined.',
                  plainEn: 'You have a strong, decisive character with natural leadership ability and the determination to overcome obstacles.' },
                { text: '伤官佩印，才华横溢，木盛则怀仁爱之心。',
                  plain: '你才华出众，有创造力，如果木元素旺盛，则心地仁爱宽厚。',
                  en: 'Talent with Resource — brilliant, Wood element brings compassion.',
                  plainEn: 'You are exceptionally talented and creative. If your Wood element is strong, you have a particularly kind and generous heart.' },
                { text: '偏财得地，口才辩给，水盛则多谋略。',
                  plain: '你口才好，善于表达和说服他人。如果水元素旺，则思维敏捷，善于谋划。',
                  en: 'Indirect Wealth grounded — eloquent speaker, Water brings strategic mind.',
                  plainEn: 'You have excellent communication skills and can persuade others effectively. A strong Water element gives you quick thinking and strategic ability.' },
                { text: '身强杀浅，假杀为权。',
                  plain: '你自身能量强，虽然官杀不重，但能将其转化为自己的权威和魄力。',
                  en: 'Strong self with weak Killings — turns authority into personal power.',
                  plainEn: 'Your self-energy is strong. Even with light authority influences, you can transform them into personal charisma and influence.' },
                { text: '杀印相生，文笔出众。',
                  plain: '你文笔好，有写作天赋，适合从事文字、学术、创作类工作。',
                  en: 'Killings producing Resource — outstanding writing ability.',
                  plainEn: 'You have a gift for writing and academic pursuits. Careers involving words, scholarship, or creative writing suit you well.' },
                { text: '七杀有制，化为权柄。',
                  plain: '你能够把压力和挑战转化为自己的权力和优势，化险为夷。',
                  en: 'Seven Killings controlled — transforms pressure into authority.',
                  plainEn: 'You have the ability to turn pressure and challenges into personal power and advantage.' },
                { text: '身强杀旺，胆大心细，敢做敢为，自傲。',
                  plain: '你胆大心细，敢于行动，自信甚至有些自负，不畏惧挑战。',
                  en: 'Strong self, strong Killings — bold yet careful, confident, daring.',
                  plainEn: 'You are bold and meticulous, ready to take action with confidence. You may come across as proud, but you don\'t shy away from challenges.' },
                { text: '杀印相生，文武双全。',
                  plain: '你文武双全，既有学识又有行动力，能文能武。',
                  en: 'Killings and Resource mutual — both scholarly and martial.',
                  plainEn: 'You are well-rounded, possessing both intellectual depth and practical capability.' },
                { text: '食神制杀，英雄独压万人。',
                  plain: '你有超群的才华和魄力，能够在众人中脱颖而出，成为领袖型人物。',
                  en: 'Output controlling Killings — a hero who stands above the crowd.',
                  plainEn: 'You have exceptional talent and charisma that makes you stand out as a natural leader among others.' },
                { text: '身强有禄，富贵自天来。',
                  plain: '你命带禄神，自身能量充足，天生有富贵之命，不愁衣食。',
                  en: 'Strong self with Salary — wealth and honor come naturally.',
                  plainEn: 'Your destiny carries natural prosperity. You have sufficient self-energy and are blessed with a comfortable life.' },
                { text: '印绶得地，慈善守成。',
                  plain: '你仁慈宽厚，善于保守成果，是可靠的守护者型人物。',
                  en: 'Resource grounded — kind, charitable, preserves achievements.',
                  plainEn: 'You are kind and reliable, good at maintaining and protecting what has been built.' },
                { text: '正印得地，心慈仁德。',
                  plain: '你心地善良，有仁爱之心，品德高尚，受人尊敬。',
                  en: 'Direct Resource grounded — kind-hearted and virtuous.',
                  plainEn: 'You have a kind and virtuous heart, earning respect from those around you.' },
                { text: '偏印得地，多学少成。',
                  plain: '你兴趣广泛，学得多但难精专，适合多领域发展但不适合深耕一门。',
                  en: 'Indirect Resource grounded — learns broadly but masters little.',
                  plainEn: 'You have wide-ranging interests and learn many things, though you may find it challenging to specialize deeply in one area.' },
                { text: '甲木得令，仁德忠厚。',
                  plain: '甲木日主得月令，为人正直忠厚，有仁德之心，是可靠之人。',
                  en: 'Jia Wood in season — loyal, honest, and virtuous.',
                  plainEn: 'With Jia Wood as your Day Master in season, you are upright, loyal, and trustworthy — someone others can count on.' },
                { text: '火土伤官，性傲刚强。',
                  plain: '你性格刚强骄傲，有主见，不轻易低头，但需要注意不要过于固执。',
                  en: 'Fire-Earth Talent — proud and strong-willed.',
                  plainEn: 'You have a strong, proud personality with firm opinions. Just be mindful not to become too stubborn.' },
                { text: '金水伤官，聪明好胜。',
                  plain: '你聪明伶俐，好胜心强，思维敏捷，反应快。',
                  en: 'Metal-Water Talent — intelligent and competitive.',
                  plainEn: 'You are sharp-minded and competitive, with quick thinking and fast reactions.' },
                { text: '日主得令，身强体健。',
                  plain: '你日主得月令之气，身体强健，精力充沛，自我意识强。',
                  en: 'Day Master in season — strong body and abundant energy.',
                  plainEn: 'Your Day Master is strong and in season, giving you good health, abundant energy, and a strong sense of self.' },
                { text: '乙木得令，柔中带刚。',
                  plain: '你外表柔和，但内心坚定，像藤蔓一样柔韧有力量。',
                  en: 'Yi Wood in season — soft exterior with inner strength.',
                  plainEn: 'You appear gentle on the outside, but inside you\'re firm and resilient — like a vine that bends but doesn\'t break.' },
                { text: '丙火得令，热情奔放。',
                  plain: '你热情似火，性格开朗，精力充沛，有感染力。',
                  en: 'Bing Fire in season — passionate and energetic.',
                  plainEn: 'You are passionate like fire — outgoing, energetic, and naturally inspiring to others.' },
                { text: '丁火得令，外柔内刚。',
                  plain: '你外表温和，内心坚定，像烛火一样持久温暖。',
                  en: 'Ding Fire in season — gentle outside, firm inside.',
                  plainEn: 'You appear gentle and warm, but your inner resolve is strong — like a candle flame that burns steadily.' },
                { text: '土重金埋，为人大方。',
                  plain: '你为人慷慨大方，不斤斤计较，但有时也会因为过于大方而吃亏。',
                  en: 'Heavy Earth buries Metal — generous and magnanimous.',
                  plainEn: 'You are generous and big-hearted, not one to sweat the small stuff, though this can sometimes work against you.' },
                { text: '水木相生，聪明仁厚。',
                  plain: '你聪明且仁厚，既有智慧又有善良的心地，是难得的好品性。',
                  en: 'Water producing Wood — intelligent and kind-hearted.',
                  plainEn: 'You combine intelligence with genuine kindness — a rare and admirable combination.' },
                { text: '火金相克，性情刚烈。',
                  plain: '你性情刚烈直率，说一不二，但需要注意控制脾气。',
                  en: 'Fire controlling Metal — fierce and straightforward temperament.',
                  plainEn: 'You have a fiery, straightforward personality. You say what you mean, but be mindful of your temper.' },
                { text: '水土混杂，心思不定。',
                  plain: '你心思多变，容易犹豫不决，需要学会专注和坚定。',
                  en: 'Water and Earth mixed — indecisive mind.',
                  plainEn: 'Your thoughts can be scattered and you may struggle with indecision. Learning to focus and commit will serve you well.' },
                { text: '金白水清，聪明伶俐。',
                  plain: '你聪明伶俐，思维清晰，判断力强，是很有智慧的人。',
                  en: 'Pure Metal and clear Water — exceptionally intelligent.',
                  plainEn: 'You have a sharp, clear mind with excellent judgment. You are naturally very intelligent.' },
                { text: '火炎土燥，性急如火。',
                  plain: '你性子急躁，做事风风火火，行动力强但缺乏耐心。',
                  en: 'Blazing Fire and dry Earth — hot-tempered and impatient.',
                  plainEn: 'You have a quick temper and act fast. Your action-oriented nature is a strength, but patience is something to cultivate.' },
                { text: '身旺无依，僧道之命。',
                  plain: '你命格身旺但无所依靠，适合追求精神层面的发展，对宗教哲学有特别缘分。',
                  en: 'Strong self without support — destined for spiritual path.',
                  plainEn: 'Your strong self-energy lacks worldly attachments, making you naturally drawn to spiritual or philosophical pursuits.' },
                { text: '甲乙木盛，仁德君子。',
                  plain: '你木元素旺盛，是仁德君子型人格，正直善良。',
                  en: 'Abundant Wood — a gentleman of virtue.',
                  plainEn: 'With strong Wood energy, you embody the qualities of a noble person — upright, kind, and principled.' },
                { text: '六乙鼠贵，外柔内刚。',
                  plain: '你外表柔顺，内心刚强，善于以柔克刚。',
                  en: 'Yi Wood noble — soft outside, firm inside.',
                  plainEn: 'You appear gentle and accommodating, but your inner strength is formidable — you overcome hardness with softness.' },
                { text: '食神生财，富贵自天来。',
                  plain: '你天生有财运，通过自己的才华和创造力可以获得财富。',
                  en: 'Output producing Wealth — prosperity comes naturally.',
                  plainEn: 'You have a natural talent for generating wealth through your creativity and skills.' },
                { text: '伤官见官，为祸百端。',
                  plain: '命局中伤官与正官相见，容易与人发生冲突，需要注意言行和人际关系。',
                  en: 'Talent meeting Officer — prone to conflicts and disputes.',
                  plainEn: 'Your chart shows a tendency for conflicts with authority. Be mindful of your words and actions in professional settings.' },
                { text: '劫财夺财，为财起争。',
                  plain: '你容易因为钱财与人发生争执，投资理财需谨慎，避免与人合伙。',
                  en: 'Rival seizing Wealth — disputes over money.',
                  plainEn: 'You may encounter financial disputes with others. Be cautious with investments and partnerships.' },
                { text: '身弱财多，富屋贫人。',
                  plain: '你身边有钱财机会但自身能量不足，难以把握，容易看着机会溜走。',
                  en: 'Weak self with much Wealth — poor person in a rich house.',
                  plainEn: 'Wealth opportunities surround you, but your energy may not be sufficient to fully capitalize on them. Strengthen yourself first.' },
                { text: '枭神夺食，衣食不足。',
                  plain: '偏印克制食神，可能会影响你的财运和口福，需要多注意。',
                  en: 'Indirect Resource seizing Output — struggles with sustenance.',
                  plainEn: 'Your chart shows a pattern where your intellectual side may override your enjoyment of life. Find balance between thinking and living.' },
                { text: '魁罡重叠，性刚难训。',
                  plain: '你命带魁罡，性格极其刚强，不轻易服从他人，适合独立创业。',
                  en: 'Multiple Kui Gang — fierce and untamable.',
                  plainEn: 'You have an extremely strong and independent personality. You don\'t easily submit to others — entrepreneurship suits you best.' }
            ]
        },

        career: {
            name: '职业',
            nameEn: 'Career',
            icon: '💼',
            rules: [
                { text: '食神泄秀，宜从事文学、书画、文教、艺术等职业。',
                  plain: '你的才华适合通过文学、艺术、教育、书画等创造性工作来展现。',
                  en: 'Output expressing elegance — suited for literature, arts, education.',
                  plainEn: 'Your talents are best expressed through creative and educational work — writing, teaching, art, and cultural pursuits.' },
                { text: '杀印相生，宜从事军事或医疗、法律业之高职及职员。',
                  plain: '你适合从事需要权威和专业性的职业，如军警、医疗、法律、管理等。',
                  en: 'Killings producing Resource — suited for military, medical, legal professions.',
                  plainEn: 'You thrive in positions of authority and expertise — military, law enforcement, medicine, law, or management.' },
                { text: '官印双全，宜学习政治、法律。',
                  plain: '你官印俱全，适合从政、法律、行政管理等体制内工作。',
                  en: 'Both Officer and Resource — suited for politics and law.',
                  plainEn: 'With both authority and scholarship in your chart, government, law, and administrative careers are natural fits.' },
                { text: '财官相生，宜学习财经、金融、财政。',
                  plain: '你财官相生，适合从事金融、财会、经济管理等领域。',
                  en: 'Wealth and Officer mutual — suited for finance and economics.',
                  plainEn: 'Your chart favors careers in finance, accounting, banking, and economic management.' },
                { text: '食神生财，宜学习商务、金融、贸易、旅游等业。',
                  plain: '你适合从事商业、贸易、金融、旅游等与人打交道又有利可图的行业。',
                  en: 'Output producing Wealth — suited for business, trade, tourism.',
                  plainEn: 'You excel in business, trade, finance, and tourism — industries that combine people skills with profit potential.' },
                { text: '身强杀旺，宜武备、警卫、军职。',
                  plain: '你身强杀旺，适合从事军警、安保、体育竞技等需要魄力的工作。',
                  en: 'Strong self, strong Killings — suited for military and security.',
                  plainEn: 'Your strong will and authoritative presence make you well-suited for military, security, or competitive sports.' },
                { text: '身弱杀旺，宜武备、警卫、军职。',
                  plain: '虽然身弱，但杀旺也适合在纪律严明的环境中发展，如军警体系。',
                  en: 'Weak self, strong Killings — suited for disciplined environments.',
                  plainEn: 'Despite your gentler nature, structured environments like the military or law enforcement can help you develop strength.' },
                { text: '食神生财，宜商务、贸易。',
                  plain: '你的才华能直接转化为财富，商业贸易是最适合你的方向。',
                  en: 'Output producing Wealth — ideal for business and trade.',
                  plainEn: 'Your talents naturally translate into profit — business and commerce are your ideal paths.' },
                { text: '伤官生财，宜商务、贸易。',
                  plain: '你的创造力和独特思维能带来商业机会，适合创新型企业。',
                  en: 'Talent producing Wealth — suited for innovative business.',
                  plainEn: 'Your creative and unconventional thinking opens up business opportunities — innovative ventures suit you.' },
                { text: '木为喜神，宜从事农林或木材制造方面的工作。',
                  plain: '你喜木，适合从事农业、林业、园艺、家具制造、造纸等与木相关的行业。',
                  en: 'Wood as favorable element — suited for agriculture and forestry.',
                  plainEn: 'With Wood as your favorable element, careers in agriculture, forestry, gardening, furniture, or paper industries are auspicious.' },
                { text: '火为喜神，宜从事演艺、餐饮、能源方面的工作。',
                  plain: '你喜火，适合演艺、餐饮、能源、照明、互联网等与火属性相关的行业。',
                  en: 'Fire as favorable element — suited for entertainment, food, energy.',
                  plainEn: 'With Fire as your favorable element, entertainment, food service, energy, tech, and creative industries are your sweet spots.' },
                { text: '土为喜神，宜从事房地产、建筑、农业方面的工作。',
                  plain: '你喜土，适合房地产、建筑、矿产、农业、仓储等稳定型行业。',
                  en: 'Earth as favorable element — suited for real estate and construction.',
                  plainEn: 'Earth-aligned careers like real estate, construction, mining, agriculture, and logistics are most favorable for you.' },
                { text: '金为喜神，宜从事金融、机械、五金方面的工作。',
                  plain: '你喜金，适合金融、机械、珠宝、五金、汽车等金属性行业。',
                  en: 'Metal as favorable element — suited for finance and machinery.',
                  plainEn: 'Metal-aligned careers like finance, engineering, jewelry, automotive, and manufacturing are your best bets.' },
                { text: '水为喜神，宜从事物流、贸易、传媒方面的工作。',
                  plain: '你喜水，适合物流、贸易、传媒、旅游、海运等流动性行业。',
                  en: 'Water as favorable element — suited for logistics, trade, media.',
                  plainEn: 'Water-aligned careers like logistics, trade, media, tourism, and shipping are most auspicious for you.' },
                { text: '身强杀浅，假杀为权，宜武职或工程界为外科医生。',
                  plain: '你适合需要权威和精准的工作，如外科医生、工程师、技术专家。',
                  en: 'Strong self, weak Killings — suited for surgery or engineering.',
                  plainEn: 'Your precision and authority suit technical professions like surgery, engineering, or specialized technical roles.' },
                { text: '正官佩印，宜从事公职或文职类工作。',
                  plain: '你适合稳定的公职工作，如公务员、教师、行政人员等。',
                  en: 'Officer with Resource — suited for civil service.',
                  plainEn: 'Stable government or administrative positions like civil service, teaching, or public administration are your natural fit.' },
                { text: '偏印当权，宜从事艺术、宗教、玄学、顾问等偏业。',
                  plain: '你适合非主流的职业方向，如艺术、玄学、心理咨询、顾问等。',
                  en: 'Indirect Resource in power — suited for arts, esoteric fields.',
                  plainEn: 'Non-mainstream careers like arts, metaphysics, counseling, and consulting are where you\'ll find fulfillment.' },
                { text: '比肩重重，宜从事合伙经营。',
                  plain: '你适合与人合伙创业，团队合作比单打独斗更适合你。',
                  en: 'Multiple Peers — suited for partnerships and joint ventures.',
                  plainEn: 'You thrive in partnerships and team ventures. Working with others brings better results than going solo.' }
            ]
        },

        wealth: {
            name: '财运',
            nameEn: 'Wealth',
            icon: '💰',
            rules: [
                { text: '日主有财，食神不缺。',
                  plain: '你日主带财，又有食神相生，财运不错，一生不愁吃穿。',
                  en: 'Day Master has Wealth, Output not lacking — financial stability.',
                  plainEn: 'Your chart shows a natural flow of wealth. You are unlikely to face serious financial hardship in life.' },
                { text: '财星入库，财富可存。',
                  plain: '你的财星入库，能够存住钱，不会轻易流失。',
                  en: 'Wealth star in storage — wealth can be preserved.',
                  plainEn: 'You have the ability to save and accumulate wealth. Money doesn\'t easily slip through your fingers.' },
                { text: '财星多透，宜防破耗。',
                  plain: '你的财星显露太多，容易招人觊觎，要注意理财和防盗。',
                  en: 'Exposed Wealth stars — watch for financial loss.',
                  plainEn: 'With wealth visible to all, be cautious about financial management and protect your assets from loss.' },
                { text: '财星归库，财富丰厚。',
                  plain: '你的财星归入财库，有机会积累可观的财富。',
                  en: 'Wealth returning to storage — substantial wealth accumulation.',
                  plainEn: 'Your chart indicates the potential for significant wealth accumulation over time.' },
                { text: '财多身弱，富屋贫人。',
                  plain: '你身边有不少赚钱机会，但自身能量不够强，难以把握。建议先提升自己。',
                  en: 'Much Wealth, weak self — poor in a rich house.',
                  plainEn: 'Wealth opportunities surround you, but your energy may not be enough to seize them. Focus on building yourself up first.' },
                { text: '财入库，富可敌国。',
                  plain: '你的财库丰厚，有积累巨额财富的潜力。',
                  en: 'Wealth in storage — potential for great riches.',
                  plainEn: 'Your chart shows the potential for accumulating substantial wealth over your lifetime.' },
                { text: '财官相生，富贵双全。',
                  plain: '你财官相生，既能赚钱又有社会地位，富贵双全的好命格。',
                  en: 'Wealth and Officer mutual — both wealth and status.',
                  plainEn: 'Your chart combines wealth potential with social status — a truly fortunate combination.' },
                { text: '财星被劫，为财起争。',
                  plain: '你的财运容易被人争夺，投资合作需谨慎，避免与人发生财务纠纷。',
                  en: 'Wealth star robbed — disputes over money.',
                  plainEn: 'Be cautious with joint investments and partnerships. Your wealth can attract competition and disputes.' },
                { text: '食神生财，富贵自来。',
                  plain: '你凭借自己的才华和创造力就能赚钱，财源滚滚而来。',
                  en: 'Output producing Wealth — prosperity through talent.',
                  plainEn: 'Your skills and creativity are your greatest wealth-generating assets. Money flows naturally from what you do best.' },
                { text: '财官印全，名利双收。',
                  plain: '你财官印三者俱全，既能赚钱、有地位，又有学识，是非常难得的命格。',
                  en: 'Wealth, Officer, Resource complete — fame and fortune.',
                  plainEn: 'Having all three — wealth, status, and knowledge — is a rare and fortunate combination. You are destined for both fame and fortune.' },
                { text: '偏财得禄，自然之财。',
                  plain: '你偏财运好，容易获得意外之财，投资理财的运气不错。',
                  en: 'Indirect Wealth at Salary — natural windfall luck.',
                  plainEn: 'You have good luck with unexpected income and investments. Windfalls come naturally to you.' },
                { text: '财星无气，为财辛苦。',
                  plain: '你的财运较弱，赚钱需要付出更多努力，劳心劳力。',
                  en: 'Weak Wealth star — hard work for money.',
                  plainEn: 'You may need to work harder than others for financial gains. Persistence and diligence will be your path to prosperity.' },
                { text: '时柱偏财，晚运亨通。',
                  plain: '你晚年财运好，越老越有钱，年轻时多积累，老来享福。',
                  en: 'Indirect Wealth in Hour Pillar — prosperity in later years.',
                  plainEn: 'Your wealth peaks in your later years. Build foundations when young, and enjoy the fruits in your golden years.' },
                { text: '日坐财星，娶妻得财。',
                  plain: '你日支坐财星，婚后财运会有提升，配偶对你的财运有帮助。',
                  en: 'Day Branch sitting on Wealth — marriage brings prosperity.',
                  plainEn: 'Your financial situation is likely to improve after marriage. Your spouse will be beneficial to your financial life.' },
                { text: '时柱财库，晚年发福。',
                  plain: '你时柱有财库，晚年财运很好，越老越富有。',
                  en: 'Wealth storage in Hour Pillar — prosperity in old age.',
                  plainEn: 'Your later years will be financially comfortable. Wealth accumulates steadily toward the end of your life.' },
                { text: '财多身弱，富屋贫人。',
                  plain: '你身边有很多赚钱机会，但因为自身能量不足，难以把握住。先提升自己。',
                  en: 'Excess Wealth, weak self — unable to grasp opportunities.',
                  plainEn: 'Financial opportunities abound, but you need to strengthen yourself first to fully benefit from them. Build your capacity.' },
                { text: '食神生财，财源广进。',
                  plain: '你的才华能带来多方面的收入来源，财路宽广。',
                  en: 'Output producing Wealth — multiple income streams.',
                  plainEn: 'Your talents open up diverse income channels. You have the potential to earn from multiple sources.' },
                { text: '财印相随，名利双收。',
                  plain: '你既有赚钱能力又有学识，名利双收的好命格。',
                  en: 'Wealth and Resource together — both fame and profit.',
                  plainEn: 'You combine earning power with knowledge and reputation — a winning combination for both money and recognition.' },
                { text: '偏财入库，财富丰厚。',
                  plain: '你的偏财入库，意外之财和投资收益能够积累下来。',
                  en: 'Indirect Wealth in storage — substantial reserves.',
                  plainEn: 'Your windfall and investment gains tend to accumulate well, building substantial reserves over time.' },
                { text: '财官双美，富贵之命。',
                  plain: '你财官都很美，既有钱又有社会地位，是富贵命格。',
                  en: 'Both Wealth and Officer beautiful — destined for prosperity.',
                  plainEn: 'Your chart shows excellence in both wealth and social standing — a truly prosperous destiny.' },
                { text: '财多身弱，妻财难守。',
                  plain: '你财运虽好但身弱，赚钱容易守钱难，需要加强理财能力。',
                  en: 'Much Wealth, weak self — hard to retain earnings.',
                  plainEn: 'While you can earn money, keeping it may be challenging. Developing strong financial management skills is key.' },
                { text: '财旺生官，因财得贵。',
                  plain: '你的财富能带来社会地位和人脉资源，越有钱地位越高。',
                  en: 'Strong Wealth producing Officer — status through wealth.',
                  plainEn: 'Your wealth will elevate your social status and connections. Money opens doors to higher circles for you.' },
                { text: '财星归库，终身不穷。',
                  plain: '你的财库充盈，一辈子都不会真正贫穷，总有经济来源。',
                  en: 'Wealth star in storage — never truly poor.',
                  plainEn: 'Your financial foundation is solid. You will always have a source of income and never face true poverty.' },
                { text: '日坐财库，无人不富。',
                  plain: '日支坐财库是非常好的财运格局，注定会富有。',
                  en: 'Day Branch on Wealth storage — destined for wealth.',
                  plainEn: 'With your Day Branch sitting on the Wealth storage, financial prosperity is built into your destiny.' },
                { text: '时上偏财，晚年大发。',
                  plain: '你时柱偏财，晚年有大财运，越老越有钱。',
                  en: 'Indirect Wealth on Hour — late-life fortune.',
                  plainEn: 'Your greatest financial success comes in your later years. The best is yet to come.' }
            ]
        },

        official: {
            name: '官运',
            nameEn: 'Authority',
            icon: '👑',
            rules: [
                { text: '杀印相生，文职掌权。',
                  plain: '你适合在体制内或大机构中担任管理职务，有实权。',
                  en: 'Killings producing Resource — civil authority.',
                  plainEn: 'You are suited for management positions in established organizations, with real decision-making power.' },
                { text: '官印相生，文职显贵。',
                  plain: '你官印相生，适合通过学术、文化、教育路线获得社会地位。',
                  en: 'Officer producing Resource — scholarly prestige.',
                  plainEn: 'Your path to status comes through scholarship, culture, and education — the academic route to influence.' },
                { text: '官星得地，一生近贵。',
                  plain: '你的官星得地，一生容易接近权贵，有贵人相助。',
                  en: 'Officer star grounded — always near the powerful.',
                  plainEn: 'You naturally attract connections with influential people. Powerful allies will help you throughout life.' },
                { text: '官星佩印，清贵之命。',
                  plain: '你官星配印，是清贵之命，有社会地位但不一定很有钱。',
                  en: 'Officer with Resource — noble but modest.',
                  plainEn: 'You have social standing and respect, though your wealth may be more modest. A life of dignity and honor.' },
                { text: '食神制杀，权威赫赫。',
                  plain: '你能够用才华驾驭权力，在权威领域有出色表现。',
                  en: 'Output controlling Killings — commanding authority.',
                  plainEn: 'Your talent gives you the ability to command authority. You excel in leadership positions.' },
                { text: '官星得禄，一生近贵。',
                  plain: '你官星得禄神，一生有贵人相助，容易获得社会地位。',
                  en: 'Officer at Salary — lifelong proximity to power.',
                  plainEn: 'You have a natural path to social standing and will find influential mentors throughout your life.' },
                { text: '杀印相生，威震边疆。',
                  plain: '你适合在需要魄力和权威的领域发展，能成为一方之主。',
                  en: 'Killings and Resource mutual — commanding presence.',
                  plainEn: 'You have the presence and authority to command respect and lead in challenging environments.' },
                { text: '官杀混杂，仕途坎坷。',
                  plain: '你的官运可能不太顺利，在职场上容易遇到是非和阻碍。',
                  en: 'Mixed Officer and Killings — bumpy career path.',
                  plainEn: 'Your career path may have ups and downs, with office politics and obstacles to navigate carefully.' },
                { text: '财官相生，名利双收。',
                  plain: '你财官相生，既有钱又有社会地位，是非常好的命格。',
                  en: 'Wealth producing Officer — both fame and fortune.',
                  plainEn: 'Money and status reinforce each other in your chart — a truly fortunate destiny.' },
                { text: '官星旺相，手握权柄。',
                  plain: '你官星旺，适合担任领导职务，有实权在手。',
                  en: 'Strong Officer star — holding real power.',
                  plainEn: 'You are destined for leadership roles with genuine authority and decision-making power.' },
                { text: '财生官旺，因财得贵。',
                  plain: '你的财富能帮你获得社会地位和权力，越有钱越有地位。',
                  en: 'Wealth producing strong Officer — status through wealth.',
                  plainEn: 'Your financial success will elevate your social standing. Wealth opens doors to power for you.' },
                { text: '官星无气，难得官位。',
                  plain: '你官星较弱，不太适合走仕途，在体制内发展空间有限。',
                  en: 'Weak Officer star — difficult to gain official position.',
                  plainEn: 'Government or bureaucratic careers may not be your strongest path. Consider other avenues for success.' },
                { text: '食神制杀，以才御权。',
                  plain: '你的才华是你驾驭权力的资本，凭借专业能力获得权威。',
                  en: 'Output controlling Killings — authority through talent.',
                  plainEn: 'Your expertise and talent are what give you authority. You earn respect through competence, not position.' },
                { text: '印星化杀，以德服人。',
                  plain: '你以德服人，用智慧和品德赢得尊重和权威。',
                  en: 'Resource transforming Killings — commanding through virtue.',
                  plainEn: 'You lead through wisdom and moral authority rather than force. People follow you because they respect you.' }
            ]
        },

        marriage: {
            name: '婚姻',
            nameEn: 'Marriage',
            icon: '💑',
            rules: [
                { text: '日坐正官，夫妻和睦。',
                  plain: '你日支坐正官，婚姻关系和谐，配偶品行端正。',
                  en: 'Day Branch on Direct Officer — harmonious marriage.',
                  plainEn: 'Your marriage is blessed with harmony. Your spouse is likely upright and virtuous.' },
                { text: '财官印全，婚姻美满。',
                  plain: '你财官印俱全，婚姻生活美满幸福，各方面都很平衡。',
                  en: 'Wealth, Officer, Resource complete — happy marriage.',
                  plainEn: 'Your chart shows all the ingredients for a happy, balanced marriage and family life.' },
                { text: '日坐财星，娶妻得财。',
                  plain: '你日支坐财星，婚后财运提升，配偶能帮你赚钱。',
                  en: 'Day Branch on Wealth — marriage brings prosperity.',
                  plainEn: 'Marriage will boost your financial situation. Your spouse contributes positively to your wealth.' },
                { text: '女命官杀混杂，婚姻不美。',
                  plain: '女命官杀混杂，感情上容易遇到复杂情况，需要谨慎选择伴侣。',
                  en: 'Mixed Officer and Killings for female — complicated love life.',
                  plainEn: 'As a woman with mixed authority stars, your love life may be complex. Choose your partner carefully.' },
                { text: '日坐比肩，夫妻争执。',
                  plain: '你日支坐比肩，夫妻之间容易因意见不合产生争执。',
                  en: 'Day Branch on Peer — marital disagreements.',
                  plainEn: 'You and your spouse may have strong opinions that clash. Learning to compromise is important.' },
                { text: '日坐七杀，配偶强势。',
                  plain: '你日支坐七杀，配偶性格强势，有主见，需要注意沟通方式。',
                  en: 'Day Branch on Seven Killings — dominant spouse.',
                  plainEn: 'Your spouse has a strong, dominant personality. Good communication is essential for harmony.' },
                { text: '官星得地，配偶优秀。',
                  plain: '你官星得地，配偶条件不错，有能力有地位。',
                  en: 'Officer star grounded — excellent spouse.',
                  plainEn: 'Your spouse is likely capable and accomplished, with good social standing.' },
                { text: '财星得地，配偶有财。',
                  plain: '你财星得地，配偶经济条件好，或者对你财运有帮助。',
                  en: 'Wealth star grounded — wealthy spouse.',
                  plainEn: 'Your spouse is likely financially well-off or will significantly help your financial situation.' },
                { text: '日坐正印，配偶仁厚。',
                  plain: '你日支坐正印，配偶性格仁厚善良，对你体贴照顾。',
                  en: 'Day Branch on Direct Resource — kind spouse.',
                  plainEn: 'Your spouse is kind, caring, and nurturing. A warm and supportive partnership.' },
                { text: '日坐偏印，配偶聪明。',
                  plain: '你日支坐偏印，配偶聪明但不一定好相处，性格可能有些独特。',
                  en: 'Day Branch on Indirect Resource — intelligent but quirky spouse.',
                  plainEn: 'Your spouse is intelligent but may have an unconventional personality. Intellectual connection is strong.' },
                { text: '女命伤官重，婚姻不顺。',
                  plain: '女命伤官过重，对婚姻有一定影响，需要学会包容和妥协。',
                  en: 'Strong Talent for female — marriage challenges.',
                  plainEn: 'As a woman with strong Talent energy, marriage may require extra patience and compromise from you.' },
                { text: '男命财星旺，妻妾成群。',
                  plain: '男命财星太旺，异性缘好，但需要注意感情专一。',
                  en: 'Strong Wealth for male — many romantic options.',
                  plainEn: 'As a man with strong Wealth energy, you attract many romantic prospects. Be mindful of commitment.' }
            ]
        },

        education: {
            name: '学业',
            nameEn: 'Education',
            icon: '📚',
            rules: [
                { text: '官印双全，必登科甲。',
                  plain: '你官印双全，学业运好，考试运佳，容易获得高学历。',
                  en: 'Both Officer and Resource — success in examinations.',
                  plainEn: 'Your chart supports academic success. You have strong potential for high educational achievement.' },
                { text: '印星得地，学历高。',
                  plain: '你印星得地，学习能力强，有获得高学历的潜力。',
                  en: 'Resource star grounded — high academic achievement.',
                  plainEn: 'You have strong learning ability and the potential for advanced degrees.' },
                { text: '官星得地，科甲有名。',
                  plain: '你官星得地，考试运好，容易在重要考试中取得好成绩。',
                  en: 'Officer star grounded — examination success.',
                  plainEn: 'You perform well in important exams and have good academic fortune.' },
                { text: '食神泄秀，文采出众。',
                  plain: '你文采好，有写作天赋，在文科、艺术类学科有优势。',
                  en: 'Output expressing elegance — literary talent.',
                  plainEn: 'You have a gift for writing and the humanities. Arts and literature are your academic strengths.' },
                { text: '杀印相生，文武双全。',
                  plain: '你文武双全，无论文科理科都能学好，全面发展。',
                  en: 'Killings and Resource mutual — well-rounded scholar.',
                  plainEn: 'You excel in both academic and practical subjects. A well-rounded talent.' },
                { text: '印绶得令，少年得志。',
                  plain: '你印绶得令，年轻时学业运好，容易少年成名。',
                  en: 'Resource in season — early academic success.',
                  plainEn: 'Your academic fortune is strong in youth. You may achieve recognition at a young age.' },
                { text: '华盖星现，艺术天赋。',
                  plain: '你命带华盖星，在艺术、玄学、哲学等非传统领域有特别天赋。',
                  en: 'Canopy star present — artistic and esoteric talent.',
                  plainEn: 'You have special talent in arts, metaphysics, and philosophy — the unconventional academic paths.' },
                { text: '文昌星现，文采斐然。',
                  plain: '你命带文昌星，文采好，在写作、文学、学术方面有天赋。',
                  en: 'Literature star present — literary brilliance.',
                  plainEn: 'Your writing and literary abilities are exceptional. Academic and literary pursuits are favored.' }
            ]
        },

        family: {
            name: '家业',
            nameEn: 'Family Business',
            icon: '🏠',
            rules: [
                { text: '年月财官印全，必受祖业。',
                  plain: '你年柱月柱财官印俱全，有祖业可继承，家庭背景不错。',
                  en: 'Year and Month have Wealth, Officer, Resource — inheritance.',
                  plainEn: 'You likely have family assets to inherit and come from a good family background.' },
                { text: '财官印全，家业兴盛。',
                  plain: '你财官印俱全，家庭事业兴旺，家族背景好。',
                  en: 'Complete Wealth, Officer, Resource — thriving family business.',
                  plainEn: 'Your family enterprise is prosperous, and you benefit from a strong family foundation.' },
                { text: '年柱官印，祖上显贵。',
                  plain: '你年柱有官印，祖上有人做官或有社会地位。',
                  en: 'Year Pillar has Officer and Resource — distinguished ancestors.',
                  plainEn: 'Your ancestors held official positions or had significant social standing.' },
                { text: '月柱财星，父母有财。',
                  plain: '你月柱有财星，父母经济条件不错，能给你提供好的物质基础。',
                  en: 'Month Pillar has Wealth — wealthy parents.',
                  plainEn: 'Your parents are financially comfortable and can provide you with a good material foundation.' },
                { text: '年柱比劫，祖业凋零。',
                  plain: '你年柱比劫多，祖业可能不太丰厚，需要靠自己奋斗。',
                  en: 'Year Pillar has Peers — diminished family inheritance.',
                  plainEn: 'Your family inheritance may be limited. You\'ll need to build your own fortune through personal effort.' },
                { text: '时柱财官，晚运兴隆。',
                  plain: '你时柱有财官，晚年运势好，越老越有福气。',
                  en: 'Hour Pillar has Wealth and Officer — prosperous later years.',
                  plainEn: 'Your later years will be prosperous and comfortable. The best part of life is yet to come.' }
            ]
        },

        parents: {
            name: '父母兄弟',
            nameEn: 'Family Ties',
            icon: '👨‍👩‍👧‍👦',
            rules: [
                { text: '年月财官印全，父母双全。',
                  plain: '你年柱月柱财官印俱全，父母双全，家庭完整幸福。',
                  en: 'Year and Month complete — both parents present.',
                  plainEn: 'You are blessed with both parents and a complete, happy family.' },
                { text: '月柱正印，母亲贤惠。',
                  plain: '你月柱正印，母亲贤惠善良，对你成长有很好的影响。',
                  en: 'Month Pillar has Direct Resource — virtuous mother.',
                  plainEn: 'Your mother is kind and virtuous, with a positive influence on your upbringing.' },
                { text: '年柱偏财，父亲能干。',
                  plain: '你年柱偏财，父亲能干有事业心，对你事业发展有启发。',
                  en: 'Year Pillar has Indirect Wealth — capable father.',
                  plainEn: 'Your father is capable and enterprising, serving as an inspiration for your career.' },
                { text: '比劫重重，兄弟众多。',
                  plain: '你比劫多，兄弟姐妹多，或者朋友多，人际关系丰富。',
                  en: 'Multiple Peers — many siblings.',
                  plainEn: 'You have many siblings or close friends. Your social circle is rich and supportive.' },
                { text: '年月财星，父母富裕。',
                  plain: '你年柱月柱有财星，父母经济条件好，家庭富裕。',
                  en: 'Year and Month have Wealth — wealthy parents.',
                  plainEn: 'Your parents are financially well-off. You grew up in a comfortable household.' },
                { text: '日支比肩，兄弟得力。',
                  plain: '你日支比肩，兄弟姐妹或朋友对你帮助很大，是你的贵人。',
                  en: 'Day Branch has Peer — helpful siblings.',
                  plainEn: 'Your siblings or close friends are very helpful to you — they are your benefactors.' },
                { text: '印星被克，母亲体弱。',
                  plain: '你印星被克，母亲可能身体不太好，需要多关心照顾。',
                  en: 'Resource star harmed — mother\'s health concerns.',
                  plainEn: 'Your mother may have health issues. Extra care and attention to her well-being is advised.' },
                { text: '财星被克，父亲缘薄。',
                  plain: '你财星被克，与父亲的缘分可能较浅，或父亲身体需要注意。',
                  en: 'Wealth star harmed — distant father relationship.',
                  plainEn: 'Your relationship with your father may be somewhat distant. His health may need attention.' }
            ]
        },

        children: {
            name: '子女',
            nameEn: 'Children',
            icon: '👶',
            rules: [
                { text: '时柱官星，子女显贵。',
                  plain: '你时柱有官星，子女将来有出息，能获得社会地位。',
                  en: 'Hour Pillar has Officer — distinguished children.',
                  plainEn: 'Your children are destined for success and social recognition.' },
                { text: '时柱食神，子女孝顺。',
                  plain: '你时柱食神，子女孝顺，晚年能享子女福。',
                  en: 'Hour Pillar has Output — filial children.',
                  plainEn: 'Your children will be filial and caring. You\'ll enjoy their support in your later years.' },
                { text: '时柱财星，子女有财。',
                  plain: '你时柱有财星，子女经济条件好，能自立更生。',
                  en: 'Hour Pillar has Wealth — prosperous children.',
                  plainEn: 'Your children will be financially successful and independent.' },
                { text: '时柱伤官，子女聪明。',
                  plain: '你时柱伤官，子女聪明伶俐，有创意，但可能比较叛逆。',
                  en: 'Hour Pillar has Talent — intelligent but rebellious children.',
                  plainEn: 'Your children are clever and creative, though they may have a rebellious streak.' },
                { text: '时柱空亡，子女缘薄。',
                  plain: '你时柱逢空亡，与子女缘分可能较浅，需要注意亲子关系。',
                  en: 'Hour Pillar empty — distant children relationship.',
                  plainEn: 'Your connection with children may be somewhat distant. Nurturing the parent-child bond is important.' },
                { text: '时柱印星，子女有学识。',
                  plain: '你时柱有印星，子女学业好，有学识，可能获得高学历。',
                  en: 'Hour Pillar has Resource — scholarly children.',
                  plainEn: 'Your children are academically gifted and likely to achieve high educational levels.' }
            ]
        },

        achievement: {
            name: '功名',
            nameEn: 'Achievement',
            icon: '🏆',
            rules: [
                { text: '官印双全，功名显达。',
                  plain: '你官印双全，在社会成就方面有很好的发展，容易获得名声和地位。',
                  en: 'Both Officer and Resource — outstanding achievement.',
                  plainEn: 'You are destined for notable social achievement and recognition.' },
                { text: '财官印全，名扬四海。',
                  plain: '你财官印俱全，有机会名扬天下，获得广泛的社会认可。',
                  en: 'Complete Wealth, Officer, Resource — worldwide fame.',
                  plainEn: 'You have the potential for widespread recognition and fame.' },
                { text: '印星得地，科甲有名。',
                  plain: '你印星得地，在学术和考试方面有成就，容易获得学位和职称。',
                  en: 'Resource star grounded — academic honors.',
                  plainEn: 'Academic achievements and formal credentials come naturally to you.' },
                { text: '食神泄秀，才艺成名。',
                  plain: '你通过自己的才华和专业技能获得名声，是实力派。',
                  en: 'Output expressing elegance — fame through talent.',
                  plainEn: 'Your fame comes from genuine talent and skill. You earn recognition through your abilities.' },
                { text: '杀印相生，功名显赫。',
                  plain: '你杀印相生，在事业上能取得显赫的成就，功成名就。',
                  en: 'Killings and Resource mutual — illustrious achievement.',
                  plainEn: 'Your career achievements will be remarkable. You are destined for great success.' },
                { text: '伤官佩印，名扬四海。',
                  plain: '你伤官配印，才华加学识，有机会名扬天下。',
                  en: 'Talent with Resource — worldwide reputation.',
                  plainEn: 'Your combination of talent and knowledge can bring you worldwide recognition.' }
            ]
        },

        health: {
            name: '健康',
            nameEn: 'Health',
            icon: '💪',
            rules: [
                { text: '身强体健，平生少病。',
                  plain: '你自身能量强，身体健康，一生很少生病。',
                  en: 'Strong self — robust health, few illnesses.',
                  plainEn: 'You have a strong constitution and enjoy good health throughout life.' },
                { text: '身弱财多，劳心劳力。',
                  plain: '你身弱财多，容易因为赚钱而劳累过度，需要注意休息。',
                  en: 'Weak self, much Wealth — prone to overwork.',
                  plainEn: 'You tend to overwork yourself pursuing wealth. Prioritize rest and self-care.' },
                { text: '火炎土燥，注意心脏。',
                  plain: '你火土过旺，需要注意心脏和血液循环方面的问题。',
                  en: 'Blazing Fire, dry Earth — watch heart health.',
                  plainEn: 'Pay attention to your heart and circulatory health. Regular check-ups are advised.' },
                { text: '水多木浮，注意肾脏。',
                  plain: '你水多木浮，需要注意肾脏和泌尿系统方面的问题。',
                  en: 'Excess Water, floating Wood — watch kidney health.',
                  plainEn: 'Be mindful of your kidney and urinary system. Stay hydrated and avoid overindulgence.' },
                { text: '金弱火旺，注意肺部。',
                  plain: '你金弱火旺，需要注意呼吸系统和肺部健康。',
                  en: 'Weak Metal, strong Fire — watch respiratory health.',
                  plainEn: 'Your respiratory system may be vulnerable. Take care of your lungs and avoid smoking.' },
                { text: '木弱金强，注意肝胆。',
                  plain: '你木弱金强，需要注意肝胆方面的问题，少喝酒。',
                  en: 'Weak Wood, strong Metal — watch liver health.',
                  plainEn: 'Your liver and gallbladder may need attention. Limit alcohol consumption.' },
                { text: '土弱木强，注意脾胃。',
                  plain: '你土弱木强，需要注意消化系统和脾胃健康。',
                  en: 'Weak Earth, strong Wood — watch digestive health.',
                  plainEn: 'Your digestive system may be sensitive. Pay attention to diet and eating habits.' },
                { text: '官杀混杂，注意外伤。',
                  plain: '你官杀混杂，出行和运动时需要注意安全，防范意外伤害。',
                  en: 'Mixed Officer and Killings — watch for injuries.',
                  plainEn: 'Be cautious with physical activities and travel. Accidents and injuries are more likely.' }
            ]
        },

        appearance: {
            name: '仪表',
            nameEn: 'Appearance',
            icon: '✨',
            rules: [
                { text: '金水相生，容貌俊美。',
                  plain: '你金水相生，容貌俊美，气质出众，给人留下好印象。',
                  en: 'Metal producing Water — handsome appearance.',
                  plainEn: 'You have attractive features and a distinguished presence that leaves a good impression.' },
                { text: '木火通明，相貌端正。',
                  plain: '你木火通明，相貌端正，气质阳光，给人正直可靠的感觉。',
                  en: 'Wood and Fire bright — dignified appearance.',
                  plainEn: 'You have a bright, upright appearance that conveys honesty and reliability.' },
                { text: '官星得地，相貌堂堂。',
                  plain: '你官星得地，相貌堂堂正正，有威严感。',
                  en: 'Officer star grounded — imposing presence.',
                  plainEn: 'You have a commanding and dignified appearance that commands respect.' },
                { text: '食神泄秀，气质清秀。',
                  plain: '你食神泄秀，气质清秀文雅，有书卷气。',
                  en: 'Output expressing elegance — refined demeanor.',
                  plainEn: 'You have a refined, scholarly air about you. Your presence is elegant and cultured.' },
                { text: '伤官得地，容貌秀丽。',
                  plain: '你伤官得地，容貌秀丽，有艺术气质。',
                  en: 'Talent grounded — beautiful appearance.',
                  plainEn: 'You have delicate, artistic features that give you a unique and attractive appearance.' },
                { text: '财星得地，体态丰满。',
                  plain: '你财星得地，体态较为丰满，有福气相。',
                  en: 'Wealth star grounded — full, prosperous appearance.',
                  plainEn: 'You have a fuller, prosperous-looking physique that suggests good fortune.' }
            ]
        },

        special: {
            name: '特殊命格',
            nameEn: 'Special Destiny',
            icon: '🔮',
            rules: [
                { text: '十灵日出生之人，一生近贵，僧道之命。',
                  plain: '你出生在特殊的日子，一生与贵人缘分深，对精神世界有特别感悟。',
                  en: 'Born on a spiritual day — close to the noble, destined for wisdom.',
                  plainEn: 'Born on a special day, you have deep connections with influential people and a natural affinity for spiritual wisdom.' },
                { text: '华盖星现，智慧过人。',
                  plain: '你命带华盖星，智慧超群，在艺术、哲学、玄学方面有特别天赋。',
                  en: 'Canopy star present — exceptional wisdom.',
                  plainEn: 'You possess exceptional intelligence with special talents in arts, philosophy, and metaphysics.' },
                { text: '天乙贵人，逢凶化吉。',
                  plain: '你命带天乙贵人，一生有贵人相助，遇到困难时总有人帮你。',
                  en: 'Heavenly Noble present — misfortune turns to fortune.',
                  plainEn: 'You have guardian angels in your life. When trouble comes, someone always appears to help you through.' },
                { text: '文昌贵人，文采出众。',
                  plain: '你命带文昌贵人，在文学、学术、考试方面有特别的好运。',
                  en: 'Literature Noble present — literary brilliance.',
                  plainEn: 'You have exceptional luck in academics, writing, and examinations. Your literary gifts are remarkable.' },
                { text: '魁罡入命，性格刚强。',
                  plain: '你命带魁罡，性格极其刚强，有领导气质，不轻易屈服。',
                  en: 'Kui Gang in destiny — fierce and unyielding.',
                  plainEn: 'You have an extremely strong-willed nature with natural leadership qualities. You don\'t submit easily.' },
                { text: '羊刃入命，性格刚烈。',
                  plain: '你命带羊刃，性格刚烈直率，行动力强，但注意控制脾气。',
                  en: 'Sheep Blade in destiny — fierce temperament.',
                  plainEn: 'You have a bold, direct personality with strong drive. Just be mindful of your temper.' },
                { text: '财官印全，三奇贵人。',
                  plain: '你财官印俱全，是难得的三奇贵人命格，各方面都很优秀。',
                  en: 'Three Wonders complete — rare and noble destiny.',
                  plainEn: 'Having all three — Wealth, Officer, and Resource — is a rare and highly auspicious destiny.' },
                { text: '金神入命，破而后立。',
                  plain: '你命带金神，人生可能会经历大的转折，但最终能获得更大的成就。',
                  en: 'Gold Spirit in destiny — great rise after fall.',
                  plainEn: 'You may experience significant life changes, but you will ultimately achieve even greater success.' },
                { text: '日德入命，品德高尚。',
                  plain: '你命带日德，品德高尚，为人正直，受人尊敬。',
                  en: 'Sun Virtue in destiny — noble character.',
                  plainEn: 'You possess high moral character and integrity. People naturally respect and trust you.' },
                { text: '将星入命，领导才能。',
                  plain: '你命带将星，有领导才能，适合担任管理职位。',
                  en: 'General Star in destiny — leadership ability.',
                  plainEn: 'You have natural leadership talent. Management and command positions suit you well.' }
            ]
        }
    };

    // Match rules based on BaZi chart data
    function getCommentary(chart, category) {
        const rules = CATEGORIES[category];
        if (!rules) return [];

        // Simple matching: return a subset of rules based on chart characteristics
        const matched = [];
        const rulesList = rules.rules;

        // Use deterministic selection based on chart data
        const dayStem = chart.dayPillar.stem;
        const dayBranch = chart.dayPillar.branch;
        const yearStem = chart.yearPillar.stem;
        const monthStem = chart.monthPillar.stem;
        const hourStem = chart.hourPillar.stem;
        const gender = chart.gender;

        // Select 3-5 rules per category based on chart characteristics
        const seed = dayStem * 100 + dayBranch * 10 + yearStem;
        const count = Math.min(5, Math.max(3, rulesList.length));

        for (let i = 0; i < count; i++) {
            const idx = (seed + i * 7 + (category.length || 0)) % rulesList.length;
            const rule = rulesList[idx];
            if (!matched.includes(rule)) {
                matched.push(rule);
            }
        }

        // Ensure at least 3 unique rules
        while (matched.length < Math.min(3, rulesList.length)) {
            const idx = (seed + matched.length * 13) % rulesList.length;
            const rule = rulesList[idx];
            if (!matched.includes(rule)) {
                matched.push(rule);
            }
        }

        return matched;
    }

    function getAllCategories() {
        return Object.keys(CATEGORIES).map(key => ({
            key,
            name: CATEGORIES[key].name,
            nameEn: CATEGORIES[key].nameEn,
            icon: CATEGORIES[key].icon,
            count: CATEGORIES[key].rules.length
        }));
    }

    function getCategoryName(key) {
        return CATEGORIES[key] ? CATEGORIES[key].name : key;
    }

    function getCategoryNameEn(key) {
        return CATEGORIES[key] ? CATEGORIES[key].nameEn : key;
    }

    return {
        CATEGORIES,
        getCommentary,
        getAllCategories,
        getCategoryName,
        getCategoryNameEn
    };
})();

if (typeof module !== 'undefined' && module.exports) {
    module.exports = CommentaryEngine;
}